name: Performance tests
on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.db }} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        db: ['postgres', 'mysql']
      fail-fast: false

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'BestPasswordEver'
        ports:
          # will assign a random free host port
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Verify MySQL connection from host
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pBestPasswordEver -e "SHOW DATABASES"
        if: matrix.db == 'mysql'

      - name: Checkout Redmine
        uses: actions/checkout@v3
        with:
          repository: redmine/redmine
          ref: c0f60e5febf1445ecf1f0b530bd418aaba8eb7c1
          path: redmine

      - name: Checkout redmine_sample_data
        uses: actions/checkout@v3
        with:
          repository: alexandermeindl/redmine_sample_data
          path: redmine/plugins/redmine_sample_data

      - name: Update package archives
        run: sudo apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          sudo apt-get install --yes --quiet
          build-essential
          cmake
          libicu-dev
          libpq-dev
          libmysqlclient-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Prepare Redmine source
        working-directory: redmine
        run: |
          cp plugins/redmine_sample_data/test/support/database-${{ matrix.db }}.yml config/database.yml
          cp plugins/redmine_sample_data/test/support/configuration.yml config/configuration.yml
          cp plugins/redmine_sample_data/test/support/additional_environment.rb config/additional_environment.rb

      - name: Install Ruby dependencies
        working-directory: redmine
        run: |
          bundle config set --local without 'development'
          bundle install --jobs=4 --retry=3

      - name: Import mysql database dump
        working-directory: redmine/plugins/redmine_sample_data/sql
        run: |
          mysqladmin --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pBestPasswordEver create redmine
          gunzip < mysql-c0f60e5fe.sql.gz | mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pBestPasswordEver redmine
        if: matrix.db == 'mysql'

      - name: Import postgres database dump
        working-directory: redmine/plugins/redmine_sample_data/sql
        env:
          PGPASSWORD: redmine
        run: |
          createdb -h localhost -p 5432 -U postgres create redmine
          gunzip < psql-c0f60e5fe.sql.gz | psql -h localhost -p 5432 -U postgres redmine
        if: matrix.db == 'postgres'

      - name: Run Redmine rake tasks
        env:
          RAILS_ENV: test
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        working-directory: redmine
        run: |
          bundle exec rake generate_secret_token
          bundle exec rake db:schema:dump

      - name: Run tests
        env:
          RAILS_ENV: test
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        working-directory: redmine
        run: |
         bundle exec rake test:benchmark plugins/redmine_sample_data/test/performance
